version: "3.8"

services:
  script-bot:
    image: ghcr.io/mrmigles/py-manager:latest
    container_name: script-bot
    restart: unless-stopped

    environment:
      # required
      BOT_TOKEN: ${BOT_TOKEN}
      OWNER_ID: ${OWNER_ID}

      DATA_DIR: /data
      TZ: Asia/Almaty

    volumes:
      - /root/volumes/py-manager:/data
